In [1]:
import requests as rq
import time
import pandas as pd
import numpy as np
import csv
from bs4 import BeautifulSoup as soup
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

In [12]:
data1 = pd.read_csv('buzzfeed1.csv', index_col=0, encoding='utf-8')
data1

,media name,media,post,link,time
0,BuzzFeed News,BuzzFeedNews,"For people under guardianship, like Britney Sp...",https://l.facebook.com/l.php?u=https%3A%2F%2Fw...,"tS0S1pthgonep11tes9mmbaeor0m 153l2r481tel, 20d221"
1,BuzzFeed News,BuzzFeedNews,Satellite footage showed a massive plume of as...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...,p
2,BuzzFeed News,BuzzFeedNews,The massive blast caused atmospheric shock wav...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...,
3,BuzzFeed News,BuzzFeedNews,Here are some of the most interesting and powe...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...,8
4,BuzzFeed News,BuzzFeedNews,A viral TikTok had some people trying throat s...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...,
...,...,...,...,...,...
1723,BuzzFeed News,BuzzFeedNews,NaN,NaN,
1724,BuzzFeed News,BuzzFeedNews,NaN,NaN,
1725,BuzzFeed News,BuzzFeedNews,NaN,NaN,8
1726,BuzzFeed News,BuzzFeedNews,NaN,NaN,0
1727,BuzzFeed News,BuzzFeedNews,NaN,NaN,

In [13]:
data2 = pd.read_csv('buzzfeed2.csv', index_col=0, encoding='utf-8')
data2

,media name,media,post,link,time
0,BuzzFeed News,BuzzFeedNews,"For people under guardianship, like Britney Sp...",https://l.facebook.com/l.php?u=https%3A%2F%2Fw...,0.0
1,BuzzFeed News,BuzzFeedNews,“The close ties across the country means it is...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...,0.0
2,BuzzFeed News,BuzzFeedNews,One hostage was released early Saturday evenin...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...,NaN
3,BuzzFeed News,BuzzFeedNews,"""This was a senseless, absolutely senseless, a...",https://l.facebook.com/l.php?u=https%3A%2F%2Fw...,NaN
4,BuzzFeed News,BuzzFeedNews,Satellite footage showed a massive plume of as...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...,NaN
...,...,...,...,...,...
273,BuzzFeed News,BuzzFeedNews,"Our favorite podcasts, newsletters, workout ap...",NaN,NaN
274,BuzzFeed News,BuzzFeedNews,"Sarah Jessica Parker, Cynthia Nixon And Kristi...",NaN,NaN
275,BuzzFeed News,BuzzFeedNews,“Britney poignantly testified about the pain h...,NaN,NaN
276,BuzzFeed News,BuzzFeedNews,"In a long-awaited ruling, Judge Amit Mehta say...",NaN,NaN
277,BuzzFeed News,BuzzFeedNews,"Headphones, routers, projectors, and more weir...",NaN,NaN

In [14]:
data1 = data1.drop('time',axis=1)
data1 = data1.dropna()
data1

,media name,media,post,link
0,BuzzFeed News,BuzzFeedNews,"For people under guardianship, like Britney Sp...",https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
1,BuzzFeed News,BuzzFeedNews,Satellite footage showed a massive plume of as...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
2,BuzzFeed News,BuzzFeedNews,The massive blast caused atmospheric shock wav...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
3,BuzzFeed News,BuzzFeedNews,Here are some of the most interesting and powe...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
4,BuzzFeed News,BuzzFeedNews,A viral TikTok had some people trying throat s...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
...,...,...,...,...
255,BuzzFeed News,BuzzFeedNews,“I very much hope to one day have a family and...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
256,BuzzFeed News,BuzzFeedNews,“We know that millions of student loan borrowe...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
257,BuzzFeed News,BuzzFeedNews,The move means federal student loan borrowers ...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
258,BuzzFeed News,BuzzFeedNews,Our terrifying experience came to an end — but...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
259,BuzzFeed News,BuzzFeedNews,"Soup dumplings, yes please",https://l.facebook.com/l.php?u=https%3A%2F%2Fw...

In [15]:
data2 = data2.drop('time',axis=1)
data2 = data2.dropna()
data2

,media name,media,post,link
0,BuzzFeed News,BuzzFeedNews,"For people under guardianship, like Britney Sp...",https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
1,BuzzFeed News,BuzzFeedNews,“The close ties across the country means it is...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
2,BuzzFeed News,BuzzFeedNews,One hostage was released early Saturday evenin...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
3,BuzzFeed News,BuzzFeedNews,"""This was a senseless, absolutely senseless, a...",https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
4,BuzzFeed News,BuzzFeedNews,Satellite footage showed a massive plume of as...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
...,...,...,...,...
255,BuzzFeed News,BuzzFeedNews,The outbreak comes as the Omicron variant has ...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
256,BuzzFeed News,BuzzFeedNews,Wait for the WIGGLE,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
257,BuzzFeed News,BuzzFeedNews,"There's no better way to say ""I don't really l...",https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
258,BuzzFeed News,BuzzFeedNews,“I very much hope to one day have a family and...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
259,BuzzFeed News,BuzzFeedNews,“We know that millions of student loan borrowe...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...

In [16]:
data3 = pd.concat([data1,data2], ignore_index=True)
data3

,media name,media,post,link
0,BuzzFeed News,BuzzFeedNews,"For people under guardianship, like Britney Sp...",https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
1,BuzzFeed News,BuzzFeedNews,Satellite footage showed a massive plume of as...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
2,BuzzFeed News,BuzzFeedNews,The massive blast caused atmospheric shock wav...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
3,BuzzFeed News,BuzzFeedNews,Here are some of the most interesting and powe...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
4,BuzzFeed News,BuzzFeedNews,A viral TikTok had some people trying throat s...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
...,...,...,...,...
515,BuzzFeed News,BuzzFeedNews,The outbreak comes as the Omicron variant has ...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
516,BuzzFeed News,BuzzFeedNews,Wait for the WIGGLE,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
517,BuzzFeed News,BuzzFeedNews,"There's no better way to say ""I don't really l...",https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
518,BuzzFeed News,BuzzFeedNews,“I very much hope to one day have a family and...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...
519,BuzzFeed News,BuzzFeedNews,“We know that millions of student loan borrowe...,https://l.facebook.com/l.php?u=https%3A%2F%2Fw...

In [17]:
data3.isnull().sum()

media name    0
media         0
post          0
link          0
dtype: int64

In [10]:
data3.duplicated().sum().sum()

#指定欄位的資料重複時即刪除資料
    #df_b.drop_duplicates('Height')

0

In [29]:
data4.to_csv('nytimes_0110.csv', encoding='utf-8')

In [14]:
data4 = data3.drop('media name',axis=1)
data4 = data4.drop('media',axis=1)
data4 = data4.drop('link',axis=1)
data4 = data4.drop('time',axis=1)

In [25]:
c = []
for i in range(len(data4)):
    c.append(i+1)
data4['ID'] = c
data4 = data4[['ID','post','article']]
data4

,ID,post,article
0,1,"991 homes were lost in the Marshall fire, one ...","LOUISVILLE, Colo. — Bryan Giles, who fled with..."
1,2,Breaking News: Dozens of antigovernment protes...,MOSCOW — Troops from a Russia-led military all...
2,3,Rep. Liz Cheney was the only Republican leader...,This episode contains strong language. On the...
3,4,In the wake of the Jan. 6 attack on the Capito...,"​​One year ago, on the very same day when feve..."
4,5,President Biden plans to call on the U.S. to r...,WASHINGTON — This anniversary of Jan. 6 marked...
...,...,...,...
584,585,"F. Sionil Jose, the author of a dozen socially...",As snowstorms sweep the East Coast of the Unit...
585,586,"Peter Bogdanovich, who died this week at 82, l...","Lani Guinier, a legal scholar whose work on vo..."
586,587,The head of a comet often glows green; the tai...,New York will require health care workers to g...
587,588,At a time when Hollywood often relegated Black...,Citigroup will dismiss unvaccinated employees ...
588,589,"A former sheriff’s deputy, Aaron Russell, face...",Sidney Poitier made history in 1964 as the fir...

In [26]:
data_post = data4.drop('article',axis=1)
data_article = data4.drop('post',axis=1)

In [27]:
data_post

      ID                                               post
0      1  991 homes were lost in the Marshall fire, one ...
1      2  Breaking News: Dozens of antigovernment protes...
2      3  Rep. Liz Cheney was the only Republican leader...
3      4  In the wake of the Jan. 6 attack on the Capito...
4      5  President Biden plans to call on the U.S. to r...
..   ...                                                ...
584  585  F. Sionil Jose, the author of a dozen socially...
585  586  Peter Bogdanovich, who died this week at 82, l...
586  587  The head of a comet often glows green; the tai...
587  588  At a time when Hollywood often relegated Black...
588  589  A former sheriff’s deputy, Aaron Russell, face...

[589 rows x 2 columns]

In [28]:
data_article

      ID                                            article
0      1  LOUISVILLE, Colo. — Bryan Giles, who fled with...
1      2  MOSCOW — Troops from a Russia-led military all...
2      3  This episode contains strong language.  On the...
3      4  ​​One year ago, on the very same day when feve...
4      5  WASHINGTON — This anniversary of Jan. 6 marked...
..   ...                                                ...
584  585  As snowstorms sweep the East Coast of the Unit...
585  586  Lani Guinier, a legal scholar whose work on vo...
586  587  New York will require health care workers to g...
587  588  Citigroup will dismiss unvaccinated employees ...
588  589  Sidney Poitier made history in 1964 as the fir...

[589 rows x 2 columns]

In [30]:
data_post.to_csv('nytimes_post.csv', encoding='utf-8')
data_article.to_csv('nytimes_article.csv', encoding='utf-8')